---
- name: Install Docker on hosts
  hosts: host_instances
  become: true
  tasks:
    - name: Installing docker
      apt:
        name: docker.io
        state: present  
        update_cache: yes
        force_apt_get: yes