
name: "Terraform Infrastructure Change Management Pipeline with Github Actions demo"
on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  pull_request:
    branches:
    - main
    paths:
      - terraform/** 
  workflow_dispatch:
    

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    steps:
      - name: Checkout repository to runner
        uses: actions/checkout@v3
      
      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          cleanup_credentials: false
      
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=capstone_project_terraform_state"

      # - name: Terraform format
      #   id: fmt
      #   run: terraform fmt -cheßck

      - name: Terraform validate
        id: validate
        run: terraform validate
      
      - name: Terraform plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve -input=false
