name: Install Docker on GCP Instances
defaults:
  run:
    shell: bash
    working-directory: ./ansible
on:
  workflow_dispatch:
    

jobs:
  install_docker:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ./inventory.yml ./playbooks/configure_instances.yaml
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GCP_SERVICE_ACCOUNT_KEY_FILE
