name: Update ansible inventory
on:
  workflow_dispatch:
    
jobs:
  update_inventory:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          cleanup_credentials: false
      
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Get Base Instance Name
        run: |
          prefix=$(gcloud compute instance-groups managed list --format='value(baseInstanceName)' --filter='name~^terraform-webservers-us')
          echo "Base instance name: $prefix"
          echo "base_instance_name=$prefix" >> $GITHUB_ENV
      
      - name: Get Instance IPs
        run: |
          prefix="${{ env.base_instance_name }}"
          echo "Using prefix: $prefix"
          ips=$(gcloud compute instances list --filter="name~^${prefix}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
          echo "Instance IPs: $ips"
          echo "instances_ips=$ips" >> $GITHUB_ENV  # Set environment variable

      - name: Update Ansible inventory
        run: |
          instances_ips="${{ env.instances_ips }}"
          echo "Updating Ansible inventory with instance IPs: $instances_ips"
          echo "[host_instances]" >> ./inventory.ini
          for ip in $instances_ips; do
            echo "$ip" >> ./inventory.ini
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./inventory.ini
          git commit -m "Update Ansible inventory with instance IPs"
          git push https://${{ secrets.RUNNER_TOKEN }}@github.com/MarkizCar20/spring-petclinic-capstone-workflows.git HEAD:main
