name: Update ansible inventory
on:
  workflow_dispatch:
    
jobs:
  update_inventory:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          cleanup_credentials: false
      
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Get Instance IPs
        id: get_ips
        run: |
          ip_addresses=$(gcloud compute instance-groups managed list-instances terraform-webservers-us \
            --zone us-central1-c \
            --format="value(instances[].networkInterfaces[0].accessConfigs[0].natIP)")
          for ip_address in $ip_addresses; do
            echo "Instance IP: $ip_address"
            # Perform actions with each IP address here
          done
          echo "instances_ips=$ip_addresses" >> $GITHUB_ENV  # Set environment variable


      - name: Update Ansible inventory
        id: update_inventory
        run: |
          instances_ips="${{ env.instances_ips }}"
          echo "[host_instances]" > ./inventory.ini
          for ip in $instances_ips; do
            echo "$ip" >> ./inventory.ini
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./inventory.ini
          git commit -m "Update Ansible inventory with instance IPs"
          git push https://${{ secrets.RUNNER_TOKEN }}@github.com/MarkizCar20/spring-petclinic-capstone-workflows.git HEAD:main